sudo: false
language: node_js

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - node_modules

script:
  - if [ "$SQUAWK" = "true" ]; then npm run squawk; fi
  - if [ "$SQUAWK" = "false" ]; then npm run lint && npm test; fi

matrix:
  include:
    - os: linux
      node_js: "4"
      env: SQUAWK=false
    - os: linux
      node_js: "6"
      env: SQUAWK=false
    - os: linux
      node_js: "7"
      env: SQUAWK=false
    - os: linux
      node_js: "8"
      env: SQUAWK=false
    - os: linux
      node_js: "7"
      env: SQUAWK=true
    - os: linux
      node_js: "8"
      env: SQUAWK=true
  allow_failures:
    - os: linux
      node_js: "7"
      env: SQUAWK=true
    - os: linux
      node_js: "8"
      env: SQUAWK=true
  fast_finish: true
